<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-LDBB7HE" failures="1" tests="1" name="Default test" time="7.819" errors="0" timestamp="2023-12-25T00:42:24 EET">
  <testcase classname="TestPackage.cartTestcases" name="fillCheckoutDetials" time="3.556">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [HANK YOU FOR YOUR ORDER] but found [THANK YOU FOR YOUR ORDER]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [HANK YOU FOR YOUR ORDER] but found [THANK YOU FOR YOUR ORDER]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at TestPackage.cartTestcases.fillCheckoutDetials(cartTestcases.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- fillCheckoutDetials -->
  <testcase classname="TestPackage.cartTestcases" name="verifyContinueShoppingButton" time="0.0">
    <ignored/>
  </testcase> <!-- verifyContinueShoppingButton -->
  <testcase classname="TestPackage.cartTestcases" name="verifyCartPageOpened" time="0.0">
    <ignored/>
  </testcase> <!-- verifyCartPageOpened -->
  <testcase classname="TestPackage.cartTestcases" name="checkOutTheorder" time="0.0">
    <ignored/>
  </testcase> <!-- checkOutTheorder -->
  <testcase classname="TestPackage.cartTestcases" name="removeIteamFromcart" time="0.0">
    <ignored/>
  </testcase> <!-- removeIteamFromcart -->
</testsuite> <!-- Default test -->
