<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LDBB7HE" failures="1" tests="5" name="CartTest" time="22.892" errors="0" timestamp="2023-12-23T14:59:59 EET">
  <testcase classname="TestPackage.cartTestcases" name="checkOutTheorder" time="3.68"/>
  <testcase classname="TestPackage.cartTestcases" name="fillCheckoutDetials" time="3.325"/>
  <testcase classname="TestPackage.cartTestcases" name="removeIteamFromcart" time="6.188">
    <failure type="java.lang.AssertionError" message="expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [0]
at TestPackage.cartTestcases.removeIteamFromcart(cartTestcases.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- removeIteamFromcart -->
  <testcase classname="TestPackage.cartTestcases" name="verifyCartPageOpened" time="1.204"/>
  <testcase classname="TestPackage.cartTestcases" name="verifyContinueShoppingButton" time="1.426"/>
</testsuite> <!-- CartTest -->
